const mentors=[['Cam Porter','UNC Football | Defensive Back',80],['Leah Mitchell','Duke Basketball | Guard',95],['Nico Alvarez','Wake Forest Soccer | Midfielder',65]];
const athletes=[{name:'Jordan Reed',sport:'Football',position:'Wide Receiver',year:'2027',school:'Myers Park High',state:'NC',gpa:'3.7',stats:'812 yards | 10 TD | 4.48 forty'},{name:'Maya Collins',sport:'Basketball',position:'Point Guard',year:'2026',school:'Cardinal Gibbons',state:'NC',gpa:'3.8',stats:'24.1 PPG | 6.8 AST | 42% 3PT'},{name:'Avery Scott',sport:'Soccer',position:'Forward',year:'2026',school:'Durham Academy',state:'NC',gpa:'3.9',stats:'22 goals | 11 assists | captain'}];
const saved=new Map();
const $=s=>document.querySelector(s);
const money=n=>`$${Number(n).toFixed(0)}`;
function modal(title,body){$('#modalBody').innerHTML=`<p class="eyebrow">Prototype flow</p><h2>${title}</h2>${body}`;$('#modal').showModal()}
function renderMentors(){const el=$('#mentors');if(!el)return;el.innerHTML=mentors.map(m=>`<article class="mentor"><span class="miniAvatar"></span><div><strong>${m[0]}</strong><br><small>${m[1]}</small></div><button class="mini" data-book="${m[0]}">${money(m[2])}</button></article>`).join('')}
function renderFeed(){const el=$('#feed');if(!el)return;const s=$('#sport').value,p=$('#position').value;const list=athletes.filter(a=>(s==='all'||a.sport===s)&&(p==='all'||a.position===p));el.innerHTML=list.length?list.map(a=>`<article class="athleteCard"><div class="athleteContent"><p class="eyebrow">${a.sport} | ${a.position}</p><h3>${a.name}</h3><p>${a.school} | Class of ${a.year} | ${a.state} | GPA ${a.gpa}</p><strong>${a.stats}</strong><div class="cardActions"><button class="button primary" data-save="${a.name}">Save Athlete</button><button class="button ghost" data-contact="${a.name}">Contact</button></div></div></article>`).join(''):'<div class="panel"><h3>No athletes match those filters.</h3><p>Try another sport or position.</p></div>'}
function renderSaved(){const el=$('#saved');if(!el)return;const list=[...saved.values()];el.innerHTML=list.length?list.map(a=>`<div class="request"><strong>${a.name}</strong><span>${a.sport} | ${a.position} | ${a.gpa} GPA</span></div>`).join(''):'<p>No saved recruits yet.</p>'}
function earnings(){if(!$('#price'))return;const price=Number($('#price').value),fee=price*.15;$('#gross').textContent=money(price);$('#fee').textContent=money(fee);$('#net').textContent=money(price-fee)}
function meal(){if(!$('#mealForm'))return;const d=Object.fromEntries(new FormData($('#mealForm')).entries());$('#mealOut').innerHTML=[['Breakfast',`Egg-white scramble, oatmeal, berries, and electrolyte water for ${d.intensity.toLowerCase()}.`],['Lunch',`Grilled chicken rice bowl with avocado, vegetables, and fruit for ${d.goal.toLowerCase()}.`],['Dinner','Salmon, sweet potatoes, greens, and Greek yogurt to support recovery.'],['Snacks','Protein smoothie, trail mix, turkey wrap, and banana before training.'],['Hydration','110-130 oz water daily, plus sodium/electrolytes around hard sessions.'],['Estimates',`${d.weight} ${d.sport} plan: 3,050 calories, 190g protein, 390g carbs, 82g fat.`]].map(x=>`<article class="plan"><strong>${x[0]}</strong><p>${x[1]}</p></article>`).join('')}
function train(){if(!$('#trainForm'))return;const d=Object.fromEntries(new FormData($('#trainForm')).entries());const copy=[`${d.goal} lift, acceleration mechanics, and position footwork.`,`${d.sport} skill block, mobility, and film study.`,'Tempo conditioning, core stability, and recovery stretch.','Power session, short-area quickness, and competitive reps.','Game-speed skill work, reaction drills, and recruiting highlight clips.','Optional light recovery and nutrition reset.'];$('#trainOut').innerHTML=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=>`<article class="plan"><strong>${day}</strong><p>${copy[i]}</p></article>`).join('')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-book]'),sv=e.target.closest('[data-save]'),ct=e.target.closest('[data-contact]'),ac=e.target.closest('[data-action]');if(b){const m=mentors.find(x=>x[0]===b.dataset.book);modal(`Book ${m[0]}`,`<p>${m[0]} offers film review, recruiting advice, training advice, nutrition advice, and college life Q&amp;A.</p><div class="earn"><span>Session price</span><strong>${money(m[2])}</strong></div><button class="button primary">Request Session</button>`)}if(sv){const a=athletes.find(x=>x.name===sv.dataset.save);saved.set(a.name,a);renderSaved();sv.textContent='Saved'}if(ct){const a=athletes.find(x=>x.name===ct.dataset.contact);modal(`Contact ${a.name}`,`<p>Because this is a verified coach account, you can initiate contact after showing recruiting interest.</p><p><strong>${a.school}</strong><br>${a.stats}<br>Class of ${a.year} | GPA ${a.gpa}</p><button class="button primary">Send Interest</button>`)}if(ac)modal(ac.dataset.action,'<p>This prototype simulates the workflow visually for investor and user demos.</p>')});
$('.close')?.addEventListener('click',()=>$('#modal').close());
$('#price')?.addEventListener('input',earnings);$('#sport')?.addEventListener('change',renderFeed);$('#position')?.addEventListener('change',renderFeed);$('#mealForm')?.addEventListener('submit',e=>{e.preventDefault();meal()});$('#trainForm')?.addEventListener('submit',e=>{e.preventDefault();train()});
renderMentors();renderFeed();renderSaved();earnings();meal();train();
